### ISSUE TITLE
Missing Item

### ISSUE THREAD

**Issue by idrp** [Coffeelot/cw-rgbpainter#1]
Item for removal of paint not added to readme.

["paint_removal_spray"] =          {["name"] = "paint_removal_spray",         ["label"] = "Paint Removal",                  ["weight"] = 1, ["type"] = "item", ["image"] = "paint_removal_spray.png", ["unique"] =false, ["useable"] = true, ['shouldClose'] = false, ["combinable"] = nil, ["description"] = "Paint Removal for Vehicles"},

**Comment by Coffeelot** [comment]
Thank you! Adding now 🙏
